const API=location.origin+'/api';
function uid(){return Number(localStorage.getItem('smpUserId')||0)}
async function api(path,options={}){const r=await fetch(API+path,{credentials:'same-origin',...options});if(r.status===401){localStorage.clear();location.replace('login.html');throw new Error('Session expired. Please login again.')}const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
async function requireAuth(expected){try{const me=await api('/me');if(expected&&me.role!==expected&&!(expected==='staff'&&(me.role==='teacher'||me.role==='admin'))){location.replace('login.html');return null}localStorage.setItem('smpUserId',me.id);localStorage.setItem('smpRole',me.role);localStorage.setItem('smpName',me.name);return me}catch(e){return null}}
async function logout(){try{await fetch(API+'/logout',{method:'POST',credentials:'same-origin'})}finally{localStorage.clear();location.replace('login.html')}}
const SCHOOL={classes:{'6':['A','B','C'],'7':['A','B','C'],'8':['A','B','C'],'9':['A','B'],'10':['A','B']}};
function toast(msg){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function openPage(id){document.querySelectorAll('.section-page').forEach(x=>x.classList.remove('active'));const p=document.getElementById(id);if(p)p.classList.add('active');document.querySelectorAll('.side-nav a[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===id));location.hash=id;window.scrollTo({top:0,behavior:'smooth'});const loads={assignments:loadAssignments,notices:loadNotices,results:loadResults,attendance:loadStudentAttendance,routine:loadRoutine,fees:loadFees,library:loadLibrary,exam:loadExams,calendar:loadCalendar,profile:loadProfile};if(loads[id])loads[id]();}
document.querySelectorAll('.side-nav a[data-page]').forEach(a=>a.onclick=e=>{e.preventDefault();openPage(a.dataset.page)});
function populateSection(c,s){const g=c.value.replace(/Grade /,'');s.innerHTML=(SCHOOL.classes[g]||['A']).map(x=>`<option>Section ${x}</option>`).join('')}
async function students(){return await (await api('/students'))}
async function loadProfile(){const box=document.querySelector('#profile .two-col');if(!box||!uid())return;const u=await api('/me');box.innerHTML=`<div class="card"><h3>Personal Information</h3><p><b>Name:</b> ${u.name}</p><p><b>Student ID:</b> ${u.login_id}</p><p><b>Email:</b> ${u.email||'Not added'}</p><p><b>Phone:</b> ${u.phone||'Not added'}</p></div><div class="card"><h3>Academic Information</h3><p><b>Grade:</b> ${u.grade}</p><p><b>Section:</b> ${u.section}</p><p><b>Roll:</b> ${u.roll}</p><p><b>Address:</b> ${u.address||'Not added'}</p></div>`}
async function loadAssignments(){const box=document.querySelector('#assignments .three-col');if(!box||!uid())return;const rows=await (await api('/student/'+uid()+'/assignments'));box.innerHTML=rows.length?rows.map(a=>`<div class="class-card"><span class="badge">${a.subject}</span><h3>${a.title}</h3><p class="muted">${a.instructions||'Assignment instructions'}</p><div class="class-meta"><span class="mini-chip">Due ${a.due_date}</span><span class="mini-chip">${a.marks} marks</span><span class="mini-chip">${a.status}</span></div><button class="btn action" onclick="submitAssignment(${a.id})" ${a.status==='Submitted'?'disabled':''}>${a.status==='Submitted'?'Submitted':'Submit Work'}</button></div>`).join(''):'<div class="card"><h3>No assignments yet</h3><p class="muted">Your teacher has not published an assignment for your section.</p></div>'}
async function submitAssignment(id){const text=prompt('Optional submission note:')||'';const r=await fetch(API+'/assignments/'+id+'/submit',{credentials:'same-origin',method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studentId:Number(uid()),text})});if(r.ok){toast('Assignment submitted and saved in SQL database');loadAssignments()}}
async function loadNotices(){const box=document.querySelector('#notices .card');if(!box)return;const rows=await (await fetch(API+'/notices')).json();box.innerHTML=rows.map(n=>`<div class="notice-item"><div><b>${n.title}</b><small class="muted" style="display:block">${n.body}<br>${new Date(n.created_at).toLocaleDateString()}</small></div><span class="tag">${n.category}</span></div>`).join('')}
async function loadResults(){const box=document.querySelector('#results .data-table');if(!box||!uid())return;const rows=await (await api('/student/'+uid()+'/results'));box.innerHTML='<tr><th>Subject</th><th>CQ</th><th>MCQ</th><th>Practical</th><th>Total</th><th>Grade</th></tr>'+rows.map(r=>{const t=r.cq+r.mcq+r.practical,g=t>=80?'A+':t>=70?'A':t>=60?'B':t>=50?'C':'F';return `<tr><td>${r.subject}</td><td>${r.cq}</td><td>${r.mcq}</td><td>${r.practical}</td><td>${t}</td><td>${g}</td></tr>`}).join('')}
async function loadStudentAttendance(){const box=document.querySelector('#attendance .card');if(!box||!uid())return;const d=await (await api('/student/'+uid()+'/attendance'));box.innerHTML=`<h3>Attendance Summary</h3><p><b>Overall Attendance: ${d.percentage}%</b></p><div class="progress"><span style="width:${d.percentage}%"></span></div><div style="margin-top:16px">${d.records.length?d.records.map(x=>`<div class="notice-item"><span>${x.date}</span><b>${x.status}</b></div>`).join(''):'<p class="muted">No attendance records have been entered yet.</p>'}</div>`}
async function loadRoutine(){const box=document.querySelector('#routine .card');if(!box||!uid())return;const rows=await (await api('/routine/'+uid()));box.innerHTML='<h3>Grade 8-B Weekly Routine</h3><div class="table-wrap"><table class="data-table"><tr><th>Day</th><th>Time</th><th>Subject</th><th>Teacher</th><th>Room</th></tr>'+rows.map(r=>`<tr><td>${r.day}</td><td>${r.time}</td><td>${r.subject}</td><td>${r.teacher}</td><td>${r.room}</td></tr>`).join('')+'</table></div>'}
async function loadFees(){const box=document.querySelector('#fees .card');if(!box||!uid())return;const rows=await (await api('/fees/'+uid()));box.innerHTML='<h3>Fee Ledger</h3><div class="table-wrap"><table class="data-table"><tr><th>Invoice</th><th>Month</th><th>Amount</th><th>Due</th><th>Status</th></tr>'+rows.map(r=>`<tr><td>${r.invoice}</td><td>${r.month}</td><td>৳${r.amount.toLocaleString()}</td><td>${r.due_date}</td><td>${r.status}</td></tr>`).join('')+'</table></div>'}
async function loadLibrary(){const box=document.querySelector('#library .card');if(!box||!uid())return;const rows=await (await api('/library/'+uid()));box.innerHTML='<h3>Issued Books</h3>'+rows.map(r=>`<div class="book"><div class="book-cover">📘</div><div><b>${r.book}</b><small class="muted" style="display:block">Due ${r.due_date} • Acc. #${r.accession}</small></div></div>`).join('')}
async function loadExams(){const box=document.querySelector('#exam .card');if(!box||!uid())return;const rows=await (await api('/exams/'+uid()));box.innerHTML='<h3>Upcoming Exams</h3><div class="table-wrap"><table class="data-table"><tr><th>Date</th><th>Exam</th><th>Subject</th><th>Time</th><th>Room</th></tr>'+rows.map(r=>`<tr><td>${r.exam_date}</td><td>${r.title}</td><td>${r.subject}</td><td>${r.start_time}–${r.end_time}</td><td>${r.room}</td></tr>`).join('')+'</table></div>'}
async function loadCalendar(){const box=document.querySelector('#calendar .card');if(!box)return;const rows=await (await api('/calendar'));box.innerHTML='<h3>Academic Calendar</h3>'+rows.map(r=>`<div class="notice-item"><div><b>${r.title}</b><small class="muted" style="display:block">${r.event_date} • ${r.description}</small></div><span class="tag">${r.category}</span></div>`).join('')}
async function loadTeacherAssignments(){const box=document.querySelector('#assignments .card:nth-child(2)');if(!box)return;const rows=await (await api('/teacher/assignments'));box.innerHTML='<h3>Recent Assignments</h3>'+rows.map(a=>`<div class="notice-item"><div><b>${a.title}</b><small class="muted" style="display:block">${a.subject} • ${a.grade}-${a.section} • Due ${a.due_date}</small></div><span class="tag">${a.submitted} submitted</span></div>`).join('')}
async function publishAssignment(){const f=document.querySelector('#assignments .card');if(!f)return;const inputs=f.querySelectorAll('input'),sel=f.querySelectorAll('select'),ta=f.querySelector('textarea');const payload={teacherId:Number(uid()),grade:(sel[0]?.value.match(/\d+/)||['8'])[0],section:(sel[0]?.value.match(/Section ([A-Z])/i)||['','B'])[1],subject:'English',title:inputs[0]?.value,dueDate:inputs[1]?.value,marks:20,instructions:ta?.value};if(!payload.title)return toast('Enter an assignment title');const r=await fetch(API+'/teacher/assignments',{credentials:'same-origin',method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(r.ok){toast('Assignment published to SQL database');if(inputs[0])inputs[0].value='';if(ta)ta.value='';loadTeacherAssignments()}}
async function saveMarks(){const rows=[...document.querySelectorAll('#marksBody tr')],allStudents=await students();for(const tr of rows){const name=tr.cells[0].textContent.replace(/^\d+ • /,'');const u=allStudents.find(x=>x.name===name);if(!u)continue;const vals=[...tr.querySelectorAll('input')].map(x=>+x.value||0);await fetch(API+'/teacher/results',{credentials:'same-origin',method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studentId:u.id,subject:'English',exam:'Mid-Term 2026',cq:vals[0],mcq:vals[1],practical:vals[2]})})}toast('Gradebook saved in SQL database')}
async function saveAttendance(){const selects=[...document.querySelectorAll('.status-select')],allStudents=await students();const records=selects.map(s=>{const u=allStudents.find(x=>x.name===s.dataset.name);return u?{studentId:u.id,status:s.value}:null}).filter(Boolean);const date=document.querySelector('#attendance input[type=date]')?.value||new Date().toISOString().slice(0,10);const r=await fetch(API+'/teacher/attendance',{credentials:'same-origin',method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({teacherId:Number(uid()),date,records})});if(r.ok)toast('Attendance saved in SQL database')}
function renderAttendance(){const c=document.getElementById('attClass'),s=document.getElementById('attSection'),box=document.getElementById('attendanceList');if(!c||!s||!box)return;const names=['Ayaan Siddique','Sara Ahmed'];box.innerHTML=names.map((n,i)=>`<div class="student-row"><span><b>${String(i+1).padStart(2,'0')}</b> • ${n}</span><select class="status-select" data-name="${n}"><option>Present</option><option>Absent</option><option>Late</option><option>Leave</option></select></div>`).join('')}
function renderMarks(){const box=document.getElementById('marksBody');if(!box)return;const names=['Ayaan Siddique','Sara Ahmed'];box.innerHTML=names.map((n,i)=>`<tr><td>${String(i+1).padStart(2,'0')} • ${n}</td><td><input class="mark" type="number" min="0" max="60" value="48"></td><td><input class="mark" type="number" min="0" max="20" value="16"></td><td><input class="mark" type="number" min="0" max="20" value="17"></td><td class="total"><b>81</b></td></tr>`).join('');box.querySelectorAll('input').forEach(inp=>inp.oninput=()=>{const tr=inp.closest('tr');tr.querySelector('.total b').textContent=[...tr.querySelectorAll('input')].reduce((a,x)=>a+(+x.value||0),0)})}
window.addEventListener('DOMContentLoaded',async()=>{const pageRole=document.body.dataset.role|| (location.pathname.includes('student-dashboard')?'student':location.pathname.includes('teacher-dashboard')?'staff':'admin');await requireAuth(pageRole);document.querySelectorAll('a[href="login.html"]').forEach(a=>{a.addEventListener('click',e=>{e.preventDefault();logout()})});renderMarks();const c=document.getElementById('attClass'),s=document.getElementById('attSection');if(c&&s){c.onchange=()=>{populateSection(c,s);renderAttendance()};s.onchange=renderAttendance;populateSection(c,s);s.value='Section B';renderAttendance()}document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast));const pub=[...document.querySelectorAll('#assignments .btn.action')].find(x=>x.textContent.includes('Publish'));if(pub){pub.removeAttribute('data-toast');pub.onclick=publishAssignment;loadTeacherAssignments()}const marks=[...document.querySelectorAll('#marks .btn.action')].find(x=>x.textContent.includes('Save Gradebook'));if(marks){marks.removeAttribute('data-toast');marks.onclick=saveMarks}const att=[...document.querySelectorAll('#attendance .btn.action')].find(x=>x.textContent.includes('Save Attendance'));if(att){att.removeAttribute('data-toast');att.onclick=saveAttendance}if(location.hash)openPage(location.hash.slice(1));});
